### ISSUE TITLE
convert.py  - _read_file function does not read in config.yaml as a dictionary

### ISSUE THREAD

**Issue by EmiFej** [KTH-dESA/OSeMBE_ECEMF#74]
I have pulled down the latest version of the workflow. It stops working at the `convert_sol `step in the `snakemake `workflow. The reason is that the `_read_file` function reads in the `config.yaml` file as a list instead of a dictionary. Here is an example of how the config.yaml is read in:

```python
['AccumulatedAnnualDemand:\n', '    indices: [REGION,FUEL,YEAR]\n', '    type: param\n', '    dtype: float\n', '    default: 0\n', 'AnnualEmissionLimit:\n', '    indices: [REGION,EMISSION,YEAR]\n', '    type: param\n', '    dtype: float\n', '    default: -1\n'
```

**Instead of:**

```yaml
AccumulatedAnnualDemand:
    indices: [REGION,FUEL,YEAR]
    type: param
    dtype: float
    default: 0
AnnualEmissionLimit:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: -1
```

The `_read_file` def shown here is taken from the otoole `utils.py`.

```python
def _read_file(open_file, ending):
    if ending == ".yaml" or ending == ".yml":
        contents = load(open_file, Loader=UniqueKeyLoader)  # typing: Dict[str, Any]
    elif ending == ".json":
        contents = json.load(open_file)  # typing: Dict
    else:
        contents = open_file.readlines()
    return contents
```
The error message during the run is shown like this:
```python
Traceback (most recent call last):
 File "C:\Users\User\Documents\ECEMF_OSeMBE\convert.py", line 37, in <module>
   sol2csv(path_sol, path_res, path_dp, path_config)
 File "C:\Users\User\Documents\ECEMF_OSeMBE\convert.py", line 16, in sol2csv
   reader = ReadGurobi(config)
             ^^^^^^^^^^^^^^^^^^  
```
Do you have any suggestions for a possible solution to this problem? The otoole environment used to load in the config.yaml file is a virtual conda environment and contains the following:
    
```yaml
name: otoole-env
dependencies:
- pandas
- pip
- pip:
  - otoole>=1.0.4
```
